In [1]:
import numpy as np
import torch
import torch.nn as nn
from ai_invader.model import EvolutionaryAI
import pygad.cnn as cnn

In [2]:
x = (1,2,3)

In [4]:
np.random.rand()

0.6624307502745201

In [3]:
input_shape = (120, 160,4)
input_shape1 = (4,120,160)
num_actions = 6

In [ ]:

input_layer = cnn.Input2D(input_shape=input_shape)

In [ ]:

conv_layer1 = cnn.Conv2D(num_filters=31,
                              kernel_size=8,
                              previous_layer=input_layer,
                              activation_function=None)

relu_layer1 = cnn.ReLU(previous_layer=conv_layer1)



In [ ]:
conv_layer2 = cnn.Conv2D(num_filters=2,
                              kernel_size=4,
                              previous_layer=relu_layer1,
                              activation_function=None)
relu_layer2 = cnn.ReLU(previous_layer=conv_layer2)


In [ ]:
max_pooling_layer = cnn.MaxPooling2D(pool_size=4,
                                          previous_layer=relu_layer2,
                                          stride=2)
conv_layer3 = cnn.Conv2D(num_filters=3,
                              kernel_size=3,
                              previous_layer=max_pooling_layer,
                              activation_function=None)
relu_layer3 = cnn.ReLU(previous_layer=conv_layer3)
flatten = cnn.Flatten(previous_layer=relu_layer3)

In [ ]:

dense_layer1 = cnn.Dense(num_neurons=128,
                              previous_layer=flatten,
                              activation_function='relu')


In [ ]:
dense_layer2 = cnn.Dense(num_neurons=num_actions,
                              previous_layer=dense_layer1,
                              activation_function='softmax')

In [ ]:

model = cnn.Model(last_layer=dense_layer2,learning_rate=0.0001)

In [ ]:
x = np.random.randn(*(4, 160, 120))

In [ ]:
model.feed_sample(x)


In [4]:
from scipy.signal import convolve2d

In [5]:
convolve2d(, in2, mode='full', boundary='fill', fillvalue=0)

SyntaxError: invalid syntax (<ipython-input-5-c4d57f26149f>, line 1)

In [13]:
from scipy import signal
from scipy import misc
ascent = misc.ascent()
print(ascent.shape)
scharr = np.array([[ -3-3j, 0-10j,  +3 -3j],
                   [-10+0j, 0+ 0j, +10 +0j],
                   [ -3+3j, 0+10j,  +3 +3j]])
print(scharr.shape) # Gx + j*Gy
grad = signal.convolve2d(ascent, scharr, boundary='symm', mode='valid')
grad.shape

(512, 512)
(3, 3)


(510, 510)

In [34]:
input_shape = (512,512,1)

input_layer = cnn.Input2D(input_shape=input_shape)
conv_test = cnn.Conv2D(num_filters=1,
                              kernel_size=3,
                              previous_layer=input_layer,
                              activation_function=None)

In [35]:
ascent2 = np.expand_dims(misc.ascent(),2)

In [36]:
ascent2.shape
# acent2_tst = np.squeeze(ascent2,2)
acent2_tst.shape

(512, 512)

In [37]:
filterer = np.squeeze(conv_test.trained_weights[0],2)

In [54]:
ex = np.expand_dims(result,2).shape
# result.shape

In [55]:
conv_test.filter_bank_size[1]/2
def clipping(res, conv_test):
    final_result = result[np.uint16(conv_test.filter_bank_size[1] / 2.0):result.shape[0] - np.uint16(
                        conv_test.filter_bank_size[1] / 2.0),
                       np.uint16(conv_test.filter_bank_size[1] / 2.0):result.shape[1] - np.uint16(
                           conv_test.filter_bank_size[1] / 2.0), :]
    return final_result
clipping(ex,conv_test)

IndexError: too many indices for array

In [45]:
conv_test.trained_weights[0]
np.sum(conv_test.trained_weights[0])

0.2982785756296037

In [59]:
%time result = convolve2d(acent2_tst,filterer,boundary='symm', mode='valid')
result

# result = result[np.uint16(self.filter_bank_size[1] / 2.0):result.shape[0] - np.uint16(
#                 self.filter_bank_size[1] / 2.0),
#                 np.uint16(self.filter_bank_size[1] / 2.0):result.shape[1] - np.uint16(
#                 self.filter_bank_size[1] / 2.0), :]


CPU times: user 14.4 ms, sys: 1.35 ms, total: 15.8 ms
Wall time: 14.7 ms


array([[24.58039646, 24.63053114, 24.75712178, ..., 34.89859335,
        34.89859335, 34.89859335],
       [24.59280191, 24.74791435, 24.75712178, ..., 34.89859335,
        34.89859335, 34.89859335],
       [24.53014033, 24.67897744, 24.68185548, ..., 34.89859335,
        34.89859335, 34.89859335],
       ...,
       [52.53968053, 52.53968053, 52.53968053, ..., 16.10070688,
        17.50210277, 18.7349232 ],
       [52.9493865 , 52.9493865 , 52.9493865 , ..., 15.84734327,
        16.55079303, 17.57491117],
       [53.09358646, 53.09358646, 53.09358646, ..., 15.06362838,
        15.53337169, 17.24158311]])

In [43]:
result-np.squeeze(n,2)

array([[ 0.26555465,  0.01524082,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.32760646,  0.19318587,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.06872755,  0.02663442, -0.13888643, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.3342822 , -0.3342822 , -0.3342822 , ...,  0.02573997,
         0.80021441, -1.57742661],
       [-0.1114274 , -0.1114274 , -0.1114274 , ...,  1.57806327,
        -0.3661163 , -0.01186352],
       [ 0.        ,  0.        ,  0.        , ...,  4.14487881,
        -0.27913723,  0.42825888]])

In [60]:
%time n = conv_test.conv_(ascent2, conv_test.trained_weights)


CPU times: user 6.66 s, sys: 43.1 ms, total: 6.7 s
Wall time: 6.77 s


In [51]:
n.shape

(510, 510, 1)

In [41]:
np.squeeze(n,2)

array([[24.31484181, 24.61529032, 24.75712178, ..., 34.89859335,
        34.89859335, 34.89859335],
       [24.26519545, 24.55472848, 24.75712178, ..., 34.89859335,
        34.89859335, 34.89859335],
       [24.59886788, 24.65234302, 24.82074191, ..., 34.89859335,
        34.89859335, 34.89859335],
       ...,
       [52.87396273, 52.87396273, 52.87396273, ..., 16.07496691,
        16.70188835, 20.31234981],
       [53.06081391, 53.06081391, 53.06081391, ..., 14.26927999,
        16.91690933, 17.58677468],
       [53.09358646, 53.09358646, 53.09358646, ..., 10.91874957,
        15.81250892, 16.81332423]])

In [124]:
# from ai_invader.model.CNN2D import Conv2DImproved
import numpy as np
import pygad.cnn as cnn
from scipy.signal import convolve2d
class Conv2DImproved(cnn.Conv2D):
    def __init__(self,num_filters, kernel_size, previous_layer, activation_function=None):
        super(Conv2DImproved,self).__init__(num_filters,kernel_size,previous_layer,activation_function)

    def conv_(self, input2D, conv_filter):
        result = np.zeros(shape=(input2D.shape[0]-self.kernel_size+1, input2D.shape[1]-self.kernel_size+1, conv_filter.shape[0]))
        input2D = np.squeeze(input2D)
        for filter_idx in range(conv_filter.shape[0]):
            # for each filter in the stack of filters
            filt = np.squeeze(conv_filter[filter_idx], 2)
            # squeeze last axis of filter off for scipy
            #print(filt.shape)
            #print(input2D.shape)
            conv = convolve2d(input2D,filt,boundary='symm', mode='valid')
            result[:,:,filter_idx]= conv

        final_result = result[np.uint16(self.filter_bank_size[1] / 2.0):result.shape[0] - np.uint16(
                                self.filter_bank_size[1] / 2.0),
                                np.uint16(self.filter_bank_size[1] / 2.0):result.shape[1] - np.uint16(
                                self.filter_bank_size[1] / 2.0), :]
        return final_result

In [125]:
input_layer = cnn.Input2D(input_shape=input_shape)
conv_test = Conv2DImproved(num_filters=2,
                              kernel_size=3,
                              previous_layer=input_layer,
                              activation_function=None)

In [126]:
conv_test.layer_output_size

(510, 510, 2)

In [127]:
#np.squeeze(ascent2).shape
input_layer.layer_output_size

(512, 512, 1)

In [128]:
conv_test.conv_(ascent2, conv_test.trained_weights)
#convolve2d(acent2_tst,filt,boundary='symm', mode='valid' )

array([[[32.69206787, -3.01081896],
        [32.96940034, -3.19026409],
        [32.96940034, -3.19026409],
        ...,
        [46.47493783, -4.49711926],
        [46.47493783, -4.49711926],
        [46.47493783, -4.49711926]],

       [[32.74763069, -3.15321191],
        [32.89017195, -3.16292914],
        [33.00816627, -3.2613198 ],
        ...,
        [46.47493783, -4.49711926],
        [46.47493783, -4.49711926],
        [46.47493783, -4.49711926]],

       [[32.72116104, -3.14925399],
        [33.08069362, -3.07919437],
        [32.97417558, -3.34796744],
        ...,
        [46.47493783, -4.49711926],
        [46.47493783, -4.49711926],
        [46.47493783, -4.49711926]],

       ...,

       [[69.92785078, -6.70878865],
        [69.92785078, -6.70878865],
        [69.92785078, -6.70878865],
        ...,
        [19.06417349,  0.99493772],
        [22.52933292, -1.86833482],
        [23.33454264, -2.097251  ]],

       [[70.04878934, -6.92446439],
        [70.04878934, -6.92

In [ ]:
import pygad

In [ ]:
sample_shape = (120, 160,4)
input_layer = pygad.cnn.Input2D(input_shape=sample_shape)
conv_layer1 = pygad.cnn.Conv2D(num_filters=8,
                               kernel_size=3,
                               previous_layer=input_layer,
                               activation_function=None)
relu_layer1 = pygad.cnn.ReLU(previous_layer=conv_layer1)
# average_pooling_layer = pygad.cnn.AveragePooling2D(pool_size=2,
#                                                    previous_layer=relu_layer1,
#                                                    stride=2)

conv_layer2 = pygad.cnn.Conv2D(num_filters=16,
                               kernel_size=3,
                               previous_layer=relu_layer1,
                               activation_function=None)
relu_layer2 = pygad.cnn.ReLU(previous_layer=conv_layer2)
# max_pooling_layer = pygad.cnn.MaxPooling2D(pool_size=2,
#                                            previous_layer=relu_layer2,
#                                            stride=2)

conv_layer3 = pygad.cnn.Conv2D(num_filters=32,
                               kernel_size=3,
                               previous_layer=relu_layer2,
                               activation_function=None)
relu_layer3 = pygad.cnn.ReLU(previous_layer=conv_layer3)
# pooling_layer = pygad.cnn.AveragePooling2D(pool_size=2,
#                                            previous_layer=relu_layer3,
#                                            stride=2)

flatten_layer = pygad.cnn.Flatten(previous_layer=relu_layer3)
dense_layer1 = pygad.cnn.Dense(num_neurons=128,
                               previous_layer=flatten_layer,
                               activation_function="relu")
dense_layer2 = pygad.cnn.Dense(num_neurons=num_actions,
                               previous_layer=dense_layer1,
                               activation_function="softmax")

model = pygad.cnn.Model(last_layer=dense_layer2,
                        epochs=1,
                        learning_rate=0.01)

model.summary()


In [ ]:
conv_layer1.filter_bank_size

In [ ]:
#eg = np.random.rand(*sample_shape)
ans = model.feed_sample(eg)
print(ans)
o = np.exp(ans)/sum(np.exp(ans))
o

In [ ]:
print(xconv_layer1.layer_output_size)

print(xrelu_layer1.layer_output_size)
print(xaverage_pooling_layer.layer_output_size)
print(xconv_layer2.layer_input_size)
print(xconv_layer2.layer_output_size) #(1, 40, 64)

In [ ]:
print(xmax_pooling_layer.layer_input_size)
print(xconv_layer3.layer_input_size)
print(xrelu_layer3.layer_output_size)
xflatten_layer.layer_output_size
# xdense_layer1.layer_output_size
# xdense_layer2.layer_output_size

In [ ]:
xinput_layer = pygad.cnn.Input2D(input_shape=input_shape)
xconv_layer1 = pygad.cnn.Conv2D(num_filters=32,
                               kernel_size=5,
                               previous_layer=xinput_layer,
                               activation_function=None)
xrelu_layer1 = pygad.cnn.ReLU(previous_layer=xconv_layer1)


xconv_layer2 = pygad.cnn.Conv2D(num_filters=64,
                               kernel_size=3,
                               previous_layer=xrelu_layer1,
                               activation_function=None)
xrelu_layer2 = pygad.cnn.ReLU(previous_layer=xconv_layer2)
xconv_layer3 = pygad.cnn.Conv2D(num_filters=64,
                               kernel_size=3,
                               previous_layer=xrelu_layer2,
                               activation_function=None)
xrelu_layer3 = pygad.cnn.ReLU(previous_layer=xconv_layer3)

xflatten_layer = pygad.cnn.Flatten(previous_layer=xrelu_layer3)
xdense_layer1 = pygad.cnn.Dense(num_neurons=512,
                               previous_layer=xflatten_layer,
                               activation_function="relu")
xdense_layer2 = pygad.cnn.Dense(num_neurons=num_actions,
                               previous_layer=xdense_layer1,
                               activation_function="softmax")

xmodel = pygad.cnn.Model(last_layer=xdense_layer2,
                        epochs=1,
                        learning_rate=0.01)

xmodel.summary()

In [ ]:
m = EvolutionaryAI(input_shape1,num_actions)
print(m)
z = np.random.rand(*(4, 120, 160))
y = torch.from_numpy(z).unsqueeze(0).type('torch.FloatTensor').to('cpu')
# m(y)

In [ ]:
traced = torch.jit.trace(m.cpu(), y)

In [ ]:
print(traced)

In [ ]:
torch.jit.save(traced, "cpu.pth")

In [ ]:
import os
! ls

In [ ]:
a.out_channels

In [ ]:
# model = cnn.Model(last_layer=dense_layer2,learning_rate=0.0001,epochs=10)

In [ ]:
x = np.random.rand(*( 120, 160,4))
x

In [ ]:
pr = xmodel.feed_sample(x)
np.exp(pr)/sum(np.exp(pr))

In [ ]:
model.get_layers()

In [ ]:
conv_layer1.initial_weights.shape

In [ ]:
model.train(train_inputs=x, train_outputs=[0,1,2,3])

In [ ]:
model.network_layers

In [ ]:
import pygad.gacnn as g

GACNN_instance = g.GACNN(model=model, num_solutions=5)
pop_vectors = g.population_as_vectors(population_networks=GACNN_instance.population_networks)

In [ ]:
from ai_invader.util import stack_frame,preprocess_frame

In [ ]:
def stack_frames(frames, state, is_new=False):
    '''
    Function combine of utility functions to preprocess the frames
    '''

    #Preprocess the frame
    frame = preprocess_frame(state, (160, 120))

    #Stack the frame
    frames = stack_frame(frames, frame, is_new)

    #Return stacked frames
    return frames


In [ ]:
def environment_solver(env, model):
    '''
    Returns a certain reward value/score that determines the fitness score/function of the neural network
    '''
    stacked_frames = stack_frames(None,env.reset(),True)
    r = 0
    s = 0
    done = False

    #Plays 1 game
    while not done:
        inp = torch.from_numpy(state).unsqueeze(0).type('torch.FloatTensor').to(device)
        output_probs = agent(inp).detach().cpu().numpy()[0]
        action = np.random.choice(range(game_actions), 1, p = output_probs).item()
        next_state, reward, done, info = env.step(action)
        next_state = stack_frames(state, next_state, False)
        state = next_state
        r = r+reward
    return r

In [ ]:
def fitness_func(solution, sol_idx):
    global GACNN_instance
    
#     predictions = GACNN_instance.population_networks[sol_idx].predict(data_inputs=data_inputs)
    model = GACNN_instance.population_networks[sol_idx]
    
    
    solution_fitness = environment_solver(env,model=model)

    return solution_fitness

def callback_generation(ga_instance):
    global GACNN_instance, last_fitness

    population_matrices = gacnn.population_as_matrices(population_networks=GACNN_instance.population_networks,
                                                       population_vectors=ga_instance.population)
    GACNN_instance.update_population_trained_weights(population_trained_weights=population_matrices)

    print("Generation = {generation}".format(generation=ga_instance.generations_completed))

In [ ]:
num_parents_mating = 4

num_generations = 10

mutation_percent_genes = 5

parent_selection_type = "sss"

crossover_type = "single_point"

mutation_type = "random"

keep_parents = 1

init_range_low = -2
init_range_high = 5

In [ ]:
ga_instance = pygad.GA(num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       initial_population=initial_population,
                       fitness_func=fitness_func,
                       mutation_percent_genes=mutation_percent_genes,
                       parent_selection_type=parent_selection_type,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       keep_parents=keep_parents,
                       callback_generation=callback_generation)

In [ ]:
ga_instance.run()

In [ ]:
ga_instance.plot_result()

In [ ]:
solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution))
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))
print("Index of the best solution : {solution_idx}".format(solution_idx=solution_idx))

In [ ]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import fashion_mnist
from sklearn.metrics import confusion_matrix

In [ ]:

from ai_invader.model.src.activation.relu import ReluLayer
from ai_invader.model.src.layers.pooling import MaxPoolLayer
from ai_invader.model.src.activation.softmax import SoftmaxLayer
from ai_invader.model.src.layers.dense import DenseLayer
from ai_invader.model.src.layers.flatten import FlattenLayer
from ai_invader.model.src.layers.convolutional import ConvLayer2D, SuperFastConvLayer2D
from ai_invader.model.src.layers.dropout import DropoutLayer
from ai_invader.model.src.model.sequential import SequentialModel
from ai_invader.model.src.utils.core import convert_categorical2one_hot, convert_prob2categorical
from ai_invader.model.src.utils.metrics import softmax_accuracy
from ai_invader.model.src.optimizers.gradient_descent import GradientDescent
from ai_invader.model.src.optimizers.rms_prop import RMSProp
from ai_invader.model.src.optimizers.adam import Adam
from ai_invader.model.src.utils.plots import lines

In [ ]:
# number of samples in the train data set
N_TRAIN_SAMPLES = 50000
# number of samples in the test data set
N_TEST_SAMPLES = 2500
# number of samples in the validation data set
N_VALID_SAMPLES = 250
# number of classes
N_CLASSES = 10
# image size
IMAGE_SIZE = 28

In [ ]:
((trainX, trainY), (testX, testY)) = fashion_mnist.load_data()
print("trainX shape:", trainX.shape)
print("trainY shape:", trainY.shape)
print("testX shape:", testX.shape)
print("testY shape:", testY.shape)

In [ ]:

X_train = trainX[:N_TRAIN_SAMPLES, :, :]
y_train = trainY[:N_TRAIN_SAMPLES]

X_test = trainX[N_TRAIN_SAMPLES:N_TRAIN_SAMPLES+N_TEST_SAMPLES, :, :]
y_test = trainY[N_TRAIN_SAMPLES:N_TRAIN_SAMPLES+N_TEST_SAMPLES]

X_valid = testX[:N_VALID_SAMPLES, :, :]
y_valid = testY[:N_VALID_SAMPLES]

In [ ]:
from ai_invader.model.src.base

X_train = X_train / 255
X_train = np.expand_dims(X_train, axis=3)
y_train = convert_categorical2one_hot(y_train)
X_test = X_test / 255
X_test = np.expand_dims(X_test, axis=3)
y_test = convert_categorical2one_hot(y_test)
X_valid = X_valid / 255
X_valid = np.expand_dims(X_valid, axis=3)
y_valid = convert_categorical2one_hot(y_valid)
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)
print("X_valid shape:", X_valid.shape)
print("y_valid shape:", y_valid.shape)

In [8]:
np.random.normal(0,1)

-1.0323391841137666

In [9]:
import math

In [11]:
def phi(x):
    'Cumulative distribution function for the standard normal distribution'
    return (1.0 + math.erf(x / math.sqrt(2.0))) / 2.0

In [14]:
phi(1/60)

0.5066487301936825

In [15]:
min([])

ValueError: min() arg is an empty sequence